services:
  - type: web
    name: pageflip
    env: node
    buildCommand: |
      npm ci
      npm run build:client
      npm run build:server
    startCommand: node dist/PageFlip/server/server.mjs
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    plan: free
    autoDeploy: true
    healthCheckPath: /
    healthCheckTimeout: 120s
